language: nodejs

services:
  - mongodb

before_install:
- npm install
- npm install -g typescript

before_script:
  - npm run build
  - sleep 15
  - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'

script:
  - npm run test

env:
  - NODE_ENV=build
