version: '3'
services:
  web:
    build: .
    ports:
     - "3000:3000"
    environment:
      NODE_ENV : docker
    volumes:
     - .:/usr/src/app
    depends_on:
    - mongo
  mongo:
    image: mongo
    ports:
    - "27017:27017"